INSERT INTO authority (authority) VALUES ('ROLE_CAS_STEALTH_CRM') ON DUPLICATE KEY UPDATE authority = 'ROLE_CAS_STEALTH_CRM';
INSERT INTO authority (authority) VALUES ('ROLE_CAS_PARTNER_CRM') ON DUPLICATE KEY UPDATE authority = 'ROLE_CAS_PARTNER_CRM';
INSERT INTO authority (authority) VALUES ('ROLE_CAS_MARKETING_ADMIN') ON DUPLICATE KEY UPDATE authority = 'ROLE_CAS_MARKETING_ADMIN';

