INSERT INTO authority (authority) VALUES ('ROLE_CAS_LISTING_ADMIN_MARKETPLACE') ON DUPLICATE KEY UPDATE authority = 'ROLE_CAS_LISTING_ADMIN_MARKETPLACE';
INSERT INTO authority (authority) VALUES ('ROLE_CAS_LISTING_PUBLISHER_MARKETPLACE') ON DUPLICATE KEY UPDATE authority = 'ROLE_CAS_LISTING_PUBLISHER_MARKETPLACE';


