INSERT INTO authority (authority) VALUES ('ROLE_CAS_CONTENT_PUBLISHER_MARKETPLACE') ON DUPLICATE KEY UPDATE authority = 'ROLE_CAS_CONTENT_PUBLISHER_MARKETPLACE';
INSERT INTO authority (authority) VALUES ('ROLE_CAS_LISTINGS_VIEW_ALL_MARKETPLACE') ON DUPLICATE KEY UPDATE authority = 'ROLE_CAS_LISTINGS_VIEW_ALL_MARKETPLACE';


